title: Sanath Kukkillaya
subtitle: A Showcase Of My Work
description: >- # this means to ignore newlines until "baseurl:"
  This is a portfolio based on the Jekyll theme devlopr-jekyll

url: "https://sanathkukkillaya.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /portfolio

# Navigation
urls:
    # - text: Home
    #   url: /
    # - text: About
    #   url: /about
    - text: Portfolio
      url: /portfolio
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Sanath Kukkillaya
author_bio: "Hi, my name is Sanath Kukkillaya. I am a professional game developer.  

👀 I’m interested in two things: programming and games. Game development lets me combine both my interests. \n
🌱 I’m currently working on creating games using Unity engine. \n
💞️ I’m looking to collaborate on a large scale AA or AAA game with a leading game studio."
author_email: "sanathkukkillaya@gmail.com"
author_location: India
author_website_url: "https://sanathkukkillaya.github.io"
typewrite-text: Eat. Sleep. Make A Game. Repeat.
hero_cover_img: linear-cover.gif # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Creative Monkey Games
              company_logo: creative-monkey-logo.png
              company_url: https://creativemonkeygames.com/
              designation: Senior Software Engineer
              description: Developing cricket games using Unity
              visibility: false
            - company_name: Juego Studios
              company_logo: juego-studios-logo.png
              company_url: https://www.juegostudio.com/
              designation: Associate Tech Lead
              description: Developed numerous mobile games of multiple genres using Unity
              visibility: true
            - company_name: ITC Infotech
              company_logo: itc-infotech-logo.png
              company_url: https://www.itcinfotech.com/
              designation: Associate IT Consultant
              description: Developed Microsoft Dynamics 365 applications for various clients
              visibility: true

# Education
author_education_details:
              - college_logo: sjec-logo.png
                college_name: St Joseph Engineering College
                college_url: https://www.sjec.ac.in/
                college_degree: Bachelor of Engineering
                description: Information Science
                visibility: true
              - college_logo: lris-logo.png
                college_name: Little Rock Indian School
                college_url: https://littlerock.edu.in/
                college_degree: Class 12
                description: Computer Science
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
# twitter_username: johndoe
github_username:  sanathkukkillaya
# facebook_username: johndoe
linkedin_username: sanathkukkillaya
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
# formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/portfolio/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /portfolio/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
